version: '3'

services:

  mysql:
    image: mysql
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: 12345678
      MYSQL_DATABASE: apato
      MYSQL_PORT: 3306
    ports:
      - 6603:3306
    volumes:
      - ./migrations:/docker-entrypoint-initdb.d
  web:
    build:
      context: .
      dockerfile: Dockerfile
    depends_on:
      - mysql
    restart: always
    ports: 
      - 80:3000
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules