ALTER TABLE Apartment ADD price INT;
ALTER TABLE User ADD location TEXT;
ALTER TABLE User ADD about TEXT;
ALTER TABLE User ADD phoneNumber TEXT;
ALTER TABLE User ADD createdAt TIMESTAMP DEFAULT CURRENT_TIMESTAMP;