ALTER TABLE User DROP username;

ALTER TABLE User ADD email VARCHAR(50) UNIQUE NOT NULL;

ALTER TABLE User
MODIFY COLUMN password VARCHAR(255) NOT NULL;

ALTER TABLE User
MODIFY id BIGINT AUTO_INCREMENT;